[project]
name = "scribe"
version = "1.0.1"
description = ""
authors = [
  { name = "Seika", email = "33862136+Seika139@users.noreply.github.com" },
]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }
dependencies = []

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=2.3.0,<3",
    "pytest>=9.1.1",
    "ruff>=0.16.1",
    "ty>=0.0.65",
    "vulture>=2.14",
    "yamllint>=1.38.0",
]

[tool.hatch.build.targets.sdist]
include = ["scribe"]

[tool.hatch.build.targets.wheel]
include = ["scribe"]

[tool.ruff]
line-length = 88
target-version = "py313"
preview = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "missing-copyright-notice",
  "missing-trailing-comma",
  # D系(Docstring)のポリシーは外部公開する部分は unignore していきたい
  "undocumented-public-module",
  "undocumented-public-class",
  "undocumented-public-method",
  "undocumented-public-function",
  "undocumented-magic-method",
  "undocumented-public-init",
  "incorrect-blank-line-before-class",    # D211 と競合するため無効化
  "multi-line-summary-second-line",    # D212 と競合するため無効化
  "missing-terminal-punctuation",
  "raw-string-in-exception",
  "f-string-in-exception",
  "boolean-type-hint-positional-argument",
  "boolean-default-value-positional-argument",
  "boolean-positional-value-in-call",
  "too-many-return-statements",
  "too-many-locals",
  "too-many-statements",
  "magic-value-comparison",
  "no-self-use",
  "print",
  "typing-only-first-party-import",
  "typing-only-third-party-import",
  "typing-only-standard-library-import",
  "raise-vanilla-args",
]

[tool.ruff.lint.flake8-tidy-imports]
# 相対インポートを禁止し、絶対インポートを強制する
ban-relative-imports = "all"

[tool.ruff.lint.mccabe]
# C901 を有効化する代わりに閾値を上げる
max-complexity = 20

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "assert",   # Allow use of assert statements in tests
  "private-member-access", # Allow use private members in tests
]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["scribe"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.13"
strict = true
exclude = ["^build/", "^tmp/", "^out/tmp/"]
